import "./globals.css";
import { Inter } from "next/font/google";

const inter: { className: string } = Inter({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Kee's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#204959]`}>{children}</body>
    </html>
  );
}
