import "./globals.css";
import { Inter } from "next/font/google";

const inter: { className: string } = Inter({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Kee's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-green-200 via-green-400 to-purple-700`}
      >
        {children}
      </body>
    </html>
  );
}
